// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
// Y O U  C A N  W R I T E  A S M  I N  L I N E  I N  C P P
//
// LOL JAVA DEFINITLY DOESNT LET YOU DO THIS
//
